const resetData = () => ({});

export const state = () => ({
  categoriesList: [],
  productsList: [],
  colorsList: [],
  countriesList: [],
  statesByCountryList: [],
  citiesByStatesList: [],
  shippingPriceList: [],
  statusList: [
    { id: "pending", ltr: "pending", rtl: "طلب جديد" },
    { id: "on hold", ltr: "on hold", rtl: "فى الإنتظار" },
    { id: "delivered", ltr: "delivered", rtl: "تم التوصيل" },
    { id: "canceled", ltr: "canceled", rtl: "ملغى" },
  ],
  // statusListRtl: ["طلب جديد", "فى الإنتظار", "تم التوصيل", "ملغى"],
  countriesLists: [
    {
      name: "Bangladesh",
      currency: "BDT",
      unicodeFlag: "🇧🇩",
      flag: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg",
      dialCode: "880",
    },
    {
      name: "Belgium",
      currency: "EUR",
      unicodeFlag: "🇧🇪",
      flag: "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg",
      dialCode: "32",
    },
    {
      name: "Burkina Faso",
      currency: "XOF",
      unicodeFlag: "🇧🇫",
      flag: "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Burkina_Faso.svg",
      dialCode: "226",
    },
    {
      name: "Bulgaria",
      currency: "BGN",
      unicodeFlag: "🇧🇬",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg",
      dialCode: "359",
    },
    {
      name: "Bosnia and Herzegovina",
      currency: "BAM",
      unicodeFlag: "🇧🇦",
      flag: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg",
      dialCode: "387",
    },
    {
      name: "Barbados",
      currency: "BBD",
      unicodeFlag: "🇧🇧",
      flag: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Barbados.svg",
      dialCode: "+1-246",
    },
    {
      name: "Wallis and Futuna",
      currency: "XPF",
      unicodeFlag: "🇼🇫",
      flag: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Flag_of_Wallis_and_Futuna.svg",
      dialCode: "681",
    },
    {
      name: "Saint Barthelemy",
      currency: "EUR",
      unicodeFlag: "🇧🇱",
      dialCode: "590",
    },
    {
      name: "Bermuda",
      currency: "BMD",
      unicodeFlag: "🇧🇲",
      flag: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bermuda.svg",
      dialCode: "+1-441",
    },
    {
      name: "Brunei",
      currency: "BND",
      unicodeFlag: "🇧🇳",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Brunei.svg",
      dialCode: "673",
    },
    {
      name: "Bolivia",
      currency: "BOB",
      unicodeFlag: "🇧🇴",
      dialCode: "591",
    },
    {
      name: "Bahrain",
      currency: "BHD",
      unicodeFlag: "🇧🇭",
      flag: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg",
      dialCode: "973",
    },
    {
      name: "Burundi",
      currency: "BIF",
      unicodeFlag: "🇧🇮",
      flag: "https://upload.wikimedia.org/wikipedia/commons/5/50/Flag_of_Burundi.svg",
      dialCode: "257",
    },
    {
      name: "Benin",
      currency: "XOF",
      unicodeFlag: "🇧🇯",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Benin.svg",
      dialCode: "229",
    },
    {
      name: "Bhutan",
      currency: "BTN",
      unicodeFlag: "🇧🇹",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/91/Flag_of_Bhutan.svg",
      dialCode: "975",
    },
    {
      name: "Jamaica",
      currency: "JMD",
      unicodeFlag: "🇯🇲",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg",
      dialCode: "+1-876",
    },
    {
      name: "Bouvet Island",
      currency: "NOK",
      unicodeFlag: "🇧🇻",
      flag: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg",
    },
    {
      name: "Botswana",
      currency: "BWP",
      unicodeFlag: "🇧🇼",
      flag: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Botswana.svg",
      dialCode: "267",
    },
    {
      name: "Samoa",
      currency: "WST",
      unicodeFlag: "🇼🇸",
      flag: "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Samoa.svg",
      dialCode: "685",
    },
    {
      name: "Bonaire, Saint Eustatius and Saba ",
      currency: "USD",
      unicodeFlag: "🇧🇶",
      dialCode: "599",
    },
    {
      name: "Brazil",
      currency: "BRL",
      unicodeFlag: "🇧🇷",
      flag: "https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg",
      dialCode: "55",
    },
    {
      name: "Bahamas",
      currency: "BSD",
      unicodeFlag: "🇧🇸",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/93/Flag_of_the_Bahamas.svg",
      dialCode: "+1-242",
    },
    {
      name: "Jersey",
      currency: "GBP",
      unicodeFlag: "🇯🇪",
      flag: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Flag_of_Jersey.svg",
      dialCode: "+44-1534",
    },
    {
      name: "Belarus",
      currency: "BYR",
      unicodeFlag: "🇧🇾",
      flag: "https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Belarus.svg",
      dialCode: "375",
    },
    {
      name: "Belize",
      currency: "BZD",
      unicodeFlag: "🇧🇿",
      flag: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Flag_of_Belize.svg",
      dialCode: "501",
    },
    {
      name: "Russia",
      currency: "RUB",
      unicodeFlag: "🇷🇺",
      dialCode: "7",
    },
    {
      name: "Rwanda",
      currency: "RWF",
      unicodeFlag: "🇷🇼",
      flag: "https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Rwanda.svg",
      dialCode: "250",
    },
    {
      name: "Serbia",
      currency: "RSD",
      unicodeFlag: "🇷🇸",
      flag: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg",
      dialCode: "381",
    },
    {
      name: "Timor-Leste",
      currency: "USD",
      unicodeFlag: "🇹🇱",
      flag: "https://upload.wikimedia.org/wikipedia/commons/2/26/Flag_of_East_Timor.svg",
      dialCode: "670",
    },
    {
      name: "Réunion",
      currency: "EUR",
      unicodeFlag: "🇷🇪",
      flag: "https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg",
      dialCode: "262",
    },
    {
      name: "Turkmenistan",
      currency: "TMT",
      unicodeFlag: "🇹🇲",
      flag: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Turkmenistan.svg",
      dialCode: "993",
    },
    {
      name: "Tajikistan",
      currency: "TJS",
      unicodeFlag: "🇹🇯",
      flag: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Tajikistan.svg",
      dialCode: "992",
    },
    {
      name: "Romania",
      currency: "RON",
      unicodeFlag: "🇷🇴",
      flag: "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg",
      dialCode: "40",
    },
    {
      name: "Tokelau",
      currency: "NZD",
      unicodeFlag: "🇹🇰",
      flag: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Flag_of_Tokelau.svg",
      dialCode: "690",
    },
    {
      name: "Guinea-Bissau",
      currency: "XOF",
      unicodeFlag: "🇬🇼",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Guinea-Bissau.svg",
      dialCode: "245",
    },
    {
      name: "Guam",
      currency: "USD",
      unicodeFlag: "🇬🇺",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/07/Flag_of_Guam.svg",
      dialCode: "+1-671",
    },
    {
      name: "Guatemala",
      currency: "GTQ",
      unicodeFlag: "🇬🇹",
      flag: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Flag_of_Guatemala.svg",
      dialCode: "502",
    },
    {
      name: "South Georgia and the South Sandwich Islands",
      currency: "GBP",
      unicodeFlag: "🇬🇸",
      flag: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_South_Georgia_and_the_South_Sandwich_Islands.svg",
    },
    {
      name: "Greece",
      currency: "EUR",
      unicodeFlag: "🇬🇷",
      flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg",
      dialCode: "30",
    },
    {
      name: "Equatorial Guinea",
      currency: "XAF",
      unicodeFlag: "🇬🇶",
      flag: "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Equatorial_Guinea.svg",
      dialCode: "240",
    },
    {
      name: "Guadeloupe",
      currency: "EUR",
      unicodeFlag: "🇬🇵",
      flag: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Flag_of_Guadeloupe_%28local%29_variant.svg",
      dialCode: "590",
    },
    {
      name: "Japan",
      currency: "JPY",
      unicodeFlag: "🇯🇵",
      flag: "https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg",
      dialCode: "81",
    },
    {
      name: "Guyana",
      currency: "GYD",
      unicodeFlag: "🇬🇾",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_Guyana.svg",
      dialCode: "592",
    },
    {
      name: "Guernsey",
      currency: "GBP",
      unicodeFlag: "🇬🇬",
      flag: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Guernsey.svg",
      dialCode: "+44-1481",
    },
    {
      name: "Georgia",
      currency: "GEL",
      unicodeFlag: "🇬🇪",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Georgia.svg",
      dialCode: "995",
    },
    {
      name: "Grenada",
      currency: "XCD",
      unicodeFlag: "🇬🇩",
      flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Grenada.svg",
      dialCode: "+1-473",
    },
    {
      name: "United Kingdom",
      currency: "GBP",
      unicodeFlag: "🇬🇧",
      flag: "https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg",
      dialCode: "44",
    },
    {
      name: "Gabon",
      currency: "XAF",
      unicodeFlag: "🇬🇦",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/04/Flag_of_Gabon.svg",
      dialCode: "241",
    },
    {
      name: "El Salvador",
      currency: "USD",
      unicodeFlag: "🇸🇻",
      flag: "https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_El_Salvador.svg",
      dialCode: "503",
    },
    {
      name: "Guinea",
      currency: "GNF",
      unicodeFlag: "🇬🇳",
      flag: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Guinea.svg",
      dialCode: "224",
    },
    {
      name: "Gambia",
      currency: "GMD",
      unicodeFlag: "🇬🇲",
      flag: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_The_Gambia.svg",
      dialCode: "220",
    },
    {
      name: "Greenland",
      currency: "DKK",
      unicodeFlag: "🇬🇱",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_Greenland.svg",
      dialCode: "299",
    },
    {
      name: "Gibraltar",
      currency: "GIP",
      unicodeFlag: "🇬🇮",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/02/Flag_of_Gibraltar.svg",
      dialCode: "350",
    },
    {
      name: "Ghana",
      currency: "GHS",
      unicodeFlag: "🇬🇭",
      flag: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg",
      dialCode: "233",
    },
    {
      name: "Oman",
      currency: "OMR",
      unicodeFlag: "🇴🇲",
      flag: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Oman.svg",
      dialCode: "968",
    },
    {
      name: "Tunisia",
      currency: "TND",
      unicodeFlag: "🇹🇳",
      flag: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg",
      dialCode: "216",
    },
    {
      name: "Jordan",
      currency: "JOD",
      unicodeFlag: "🇯🇴",
      flag: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg",
      dialCode: "962",
    },
    {
      name: "Croatia",
      currency: "HRK",
      unicodeFlag: "🇭🇷",
      flag: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg",
      dialCode: "385",
    },
    {
      name: "Haiti",
      currency: "HTG",
      unicodeFlag: "🇭🇹",
      flag: "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg",
      dialCode: "509",
    },
    {
      name: "Hungary",
      currency: "HUF",
      unicodeFlag: "🇭🇺",
      flag: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg",
      dialCode: "36",
    },
    {
      name: "Hong Kong",
      currency: "HKD",
      unicodeFlag: "🇭🇰",
      flag: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Flag_of_Hong_Kong.svg",
      dialCode: "852",
    },
    {
      name: "Honduras",
      currency: "HNL",
      unicodeFlag: "🇭🇳",
      flag: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Naval_Ensign_of_Honduras.svg",
      dialCode: "504",
    },
    {
      name: "Heard Island and McDonald Islands",
      currency: "AUD",
      unicodeFlag: "🇭🇲",
      flag: "https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Australia_%28converted%29.svg",
      dialCode: " ",
    },
    {
      name: "Venezuela",
      currency: "VEF",
      unicodeFlag: "🇻🇪",
      dialCode: "58",
    },
    {
      name: "Vatican City State (Holy See)",
      currency: "EUR",
      unicodeFlag: "🇻🇦",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_the_Vatican_City.svg",
      dialCode: "379",
    },
    {
      name: "Puerto Rico",
      currency: "USD",
      unicodeFlag: "🇵🇷",
      flag: "https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_Puerto_Rico.svg",
      dialCode: "+1-787 and 1-939",
    },
    {
      name: "Palestinian Territory",
      currency: "ILS",
      unicodeFlag: "🇵🇸",
      dialCode: "970",
    },
    {
      name: "Palau",
      currency: "USD",
      unicodeFlag: "🇵🇼",
      flag: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Palau.svg",
      dialCode: "680",
    },
    {
      name: "Portugal",
      currency: "EUR",
      unicodeFlag: "🇵🇹",
      flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg",
      dialCode: "351",
    },
    {
      name: "Svalbard and Jan Mayen",
      currency: "NOK",
      unicodeFlag: "🇸🇯",
      dialCode: "47",
    },
    {
      name: "Paraguay",
      currency: "PYG",
      unicodeFlag: "🇵🇾",
      flag: "https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Paraguay.svg",
      dialCode: "595",
    },
    {
      name: "Iraq",
      currency: "IQD",
      unicodeFlag: "🇮🇶",
      flag: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Iraq.svg",
      dialCode: "964",
    },
    {
      name: "Panama",
      currency: "PAB",
      unicodeFlag: "🇵🇦",
      flag: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Flag_of_Panama.svg",
      dialCode: "507",
    },
    {
      name: "French Polynesia",
      currency: "XPF",
      unicodeFlag: "🇵🇫",
      flag: "https://upload.wikimedia.org/wikipedia/commons/d/db/Flag_of_French_Polynesia.svg",
      dialCode: "689",
    },
    {
      name: "Papua New Guinea",
      currency: "PGK",
      unicodeFlag: "🇵🇬",
      flag: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Flag_of_Papua_New_Guinea.svg",
      dialCode: "675",
    },
    {
      name: "Peru",
      currency: "PEN",
      unicodeFlag: "🇵🇪",
      flag: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Peru.svg",
      dialCode: "51",
    },
    {
      name: "Pakistan",
      currency: "PKR",
      unicodeFlag: "🇵🇰",
      flag: "https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg",
      dialCode: "92",
    },
    {
      name: "Philippines",
      currency: "PHP",
      unicodeFlag: "🇵🇭",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg",
      dialCode: "63",
    },
    {
      name: "Pitcairn",
      currency: "NZD",
      unicodeFlag: "🇵🇳",
      flag: "https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_the_Pitcairn_Islands.svg",
      dialCode: "870",
    },
    {
      name: "Poland",
      currency: "PLN",
      unicodeFlag: "🇵🇱",
      flag: "https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg",
      dialCode: "48",
    },
    {
      name: "Saint Pierre and Miquelon",
      currency: "EUR",
      unicodeFlag: "🇵🇲",
      flag: "https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_Saint-Pierre_and_Miquelon.svg",
      dialCode: "508",
    },
    {
      name: "Zambia",
      currency: "ZMK",
      unicodeFlag: "🇿🇲",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Zambia.svg",
      dialCode: "260",
    },
    {
      name: "Western Sahara",
      currency: "MAD",
      unicodeFlag: "🇪🇭",
      dialCode: "212",
    },
    {
      name: "Estonia",
      currency: "EUR",
      unicodeFlag: "🇪🇪",
      flag: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg",
      dialCode: "372",
    },
    {
      name: "Egypt",
      currency: "EGP",
      unicodeFlag: "🇪🇬",
      flag: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg",
      dialCode: "20",
    },
    {
      name: "Cocos (Keeling) Islands",
      currency: "AUD",
      unicodeFlag: "🇨🇨",
      flag: "https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Cocos_%28Keeling%29_Islands.svg",
      dialCode: "166",
    },
    {
      name: "South Africa",
      currency: "ZAR",
      unicodeFlag: "🇿🇦",
      flag: "https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg",
      dialCode: "27",
    },
    {
      name: "Ecuador",
      currency: "USD",
      unicodeFlag: "🇪🇨",
      flag: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg",
      dialCode: "593",
    },
    {
      name: "Italy",
      currency: "EUR",
      unicodeFlag: "🇮🇹",
      flag: "https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg",
      dialCode: "39",
    },
    {
      name: "Vietnam",
      currency: "VND",
      unicodeFlag: "🇻🇳",
      flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg",
      dialCode: "84",
    },
    {
      name: "Solomon Islands",
      currency: "SBD",
      unicodeFlag: "🇸🇧",
      flag: "https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Solomon_Islands.svg",
      dialCode: "677",
    },
    {
      name: "Ethiopia",
      currency: "ETB",
      unicodeFlag: "🇪🇹",
      flag: "https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Ethiopia.svg",
      dialCode: "251",
    },
    {
      name: "Somalia",
      currency: "SOS",
      unicodeFlag: "🇸🇴",
      flag: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Somalia.svg",
      dialCode: "252",
    },
    {
      name: "Zimbabwe",
      currency: "ZWL",
      unicodeFlag: "🇿🇼",
      flag: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg",
      dialCode: "263",
    },
    {
      name: "Saudi Arabia",
      currency: "SAR",
      unicodeFlag: "🇸🇦",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg",
      dialCode: "966",
    },
    {
      name: "Spain",
      currency: "EUR",
      unicodeFlag: "🇪🇸",
      flag: "https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg",
      dialCode: "34",
    },
    {
      name: "Eritrea",
      currency: "ERN",
      unicodeFlag: "🇪🇷",
      flag: "https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Eritrea.svg",
      dialCode: "291",
    },
    {
      name: "Montenegro",
      currency: "EUR",
      unicodeFlag: "🇲🇪",
      flag: "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Montenegro.svg",
      dialCode: "382",
    },
    {
      name: "Moldova",
      currency: "MDL",
      unicodeFlag: "🇲🇩",
      dialCode: "373",
    },
    {
      name: "Madagascar",
      currency: "MGA",
      unicodeFlag: "🇲🇬",
      flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Madagascar.svg",
      dialCode: "261",
    },
    {
      name: "Saint Martin",
      currency: "EUR",
      unicodeFlag: "🇲🇫",
      dialCode: "590",
    },
    {
      name: "Morocco",
      currency: "MAD",
      unicodeFlag: "🇲🇦",
      flag: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg",
      dialCode: "212",
    },
    {
      name: "Monaco",
      currency: "EUR",
      unicodeFlag: "🇲🇨",
      flag: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Flag_of_Monaco.svg",
      dialCode: "377",
    },
    {
      name: "Uzbekistan",
      currency: "UZS",
      unicodeFlag: "🇺🇿",
      flag: "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Uzbekistan.svg",
      dialCode: "998",
    },
    {
      name: "Myanmar",
      currency: "MMK",
      unicodeFlag: "🇲🇲",
      flag: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Myanmar.svg",
      dialCode: "95",
    },
    {
      name: "Mali",
      currency: "XOF",
      unicodeFlag: "🇲🇱",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Mali.svg",
      dialCode: "223",
    },
    {
      name: "Macau",
      currency: "MOP",
      unicodeFlag: "🇲🇴",
      flag: "https://upload.wikimedia.org/wikipedia/commons/6/63/Flag_of_Macau.svg",
      dialCode: "853",
    },
    {
      name: "Mongolia",
      currency: "MNT",
      unicodeFlag: "🇲🇳",
      flag: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Mongolia.svg",
      dialCode: "976",
    },
    {
      name: "Marshall Islands",
      currency: "USD",
      unicodeFlag: "🇲🇭",
      flag: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Flag_of_the_Marshall_Islands.svg",
      dialCode: "692",
    },
    {
      name: "Macedonia",
      currency: "MKD",
      unicodeFlag: "🇲🇰",
      dialCode: "389",
    },
    {
      name: "Mauritius",
      currency: "MUR",
      unicodeFlag: "🇲🇺",
      flag: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Mauritius.svg",
      dialCode: "230",
    },
    {
      name: "Malta",
      currency: "EUR",
      unicodeFlag: "🇲🇹",
      flag: "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Malta.svg",
      dialCode: "356",
    },
    {
      name: "Malawi",
      currency: "MWK",
      unicodeFlag: "🇲🇼",
      flag: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Flag_of_Malawi.svg",
      dialCode: "265",
    },
    {
      name: "Maldives",
      currency: "MVR",
      unicodeFlag: "🇲🇻",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Maldives.svg",
      dialCode: "960",
    },
    {
      name: "Martinique",
      currency: "EUR",
      unicodeFlag: "🇲🇶",
      flag: "https://upload.wikimedia.org/wikipedia/commons/6/64/Snake_Flag_of_Martinique.svg",
      dialCode: "596",
    },
    {
      name: "Northern Mariana Islands",
      currency: "USD",
      unicodeFlag: "🇲🇵",
      flag: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Flag_of_the_Northern_Mariana_Islands.svg",
      dialCode: "+1-670",
    },
    {
      name: "Montserrat",
      currency: "XCD",
      unicodeFlag: "🇲🇸",
      flag: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Montserrat.svg",
      dialCode: "+1-664",
    },
    {
      name: "Mauritania",
      currency: "MRO",
      unicodeFlag: "🇲🇷",
      flag: "https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Mauritania.svg",
      dialCode: "222",
    },
    {
      name: "Isle of Man",
      currency: "GBP",
      unicodeFlag: "🇮🇲",
      flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_the_Isle_of_Man.svg",
      dialCode: "+44-1624",
    },
    {
      name: "Uganda",
      currency: "UGX",
      unicodeFlag: "🇺🇬",
      flag: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Uganda.svg",
      dialCode: "256",
    },
    {
      name: "Tanzania",
      currency: "TZS",
      unicodeFlag: "🇹🇿",
      dialCode: "255",
    },
    {
      name: "Malaysia",
      currency: "MYR",
      unicodeFlag: "🇲🇾",
      flag: "https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg",
      dialCode: "60",
    },
    {
      name: "Mexico",
      currency: "MXN",
      unicodeFlag: "🇲🇽",
      flag: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg",
      dialCode: "52",
    },
    {
      name: "Israel",
      currency: "ILS",
      unicodeFlag: "🇮🇱",
      flag: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg",
      dialCode: "972",
    },
    {
      name: "France",
      currency: "EUR",
      unicodeFlag: "🇫🇷",
      flag: "https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg",
      dialCode: "33",
    },
    {
      name: "British Indian Ocean Territory",
      currency: "USD",
      unicodeFlag: "🇮🇴",
      flag: "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg",
      dialCode: "246",
    },
    {
      name: "Saint Helena",
      currency: "SHP",
      unicodeFlag: "🇸🇭",
      dialCode: "290",
    },
    {
      name: "Finland",
      currency: "EUR",
      unicodeFlag: "🇫🇮",
      flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg",
      dialCode: "358",
    },
    {
      name: "Fiji",
      currency: "FJD",
      unicodeFlag: "🇫🇯",
      flag: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Fiji.svg",
      dialCode: "679",
    },
    {
      name: "Falkland Islands",
      currency: "FKP",
      unicodeFlag: "🇫🇰",
      flag: "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_Falkland_Islands.svg",
      dialCode: "500",
    },
    {
      name: "Micronesia",
      currency: "USD",
      unicodeFlag: "🇫🇲",
      dialCode: "691",
    },
    {
      name: "Faroe Islands",
      currency: "DKK",
      unicodeFlag: "🇫🇴",
      flag: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Flag_of_the_Faroe_Islands.svg",
      dialCode: "298",
    },
    {
      name: "Nicaragua",
      currency: "NIO",
      unicodeFlag: "🇳🇮",
      flag: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Nicaragua.svg",
      dialCode: "505",
    },
    {
      name: "Netherlands",
      currency: "EUR",
      unicodeFlag: "🇳🇱",
      flag: "https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg",
      dialCode: "31",
    },
    {
      name: "Norway",
      currency: "NOK",
      unicodeFlag: "🇳🇴",
      flag: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg",
      dialCode: "47",
    },
    {
      name: "Namibia",
      currency: "NAD",
      unicodeFlag: "🇳🇦",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Namibia.svg",
      dialCode: "264",
    },
    {
      name: "Vanuatu",
      currency: "VUV",
      unicodeFlag: "🇻🇺",
      flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Vanuatu.svg",
      dialCode: "678",
    },
    {
      name: "New Caledonia",
      currency: "XPF",
      unicodeFlag: "🇳🇨",
      flag: "https://upload.wikimedia.org/wikipedia/commons/2/26/Flags_of_New_Caledonia.svg",
      dialCode: "687",
    },
    {
      name: "Niger",
      currency: "XOF",
      unicodeFlag: "🇳🇪",
      flag: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Flag_of_Niger.svg",
      dialCode: "227",
    },
    {
      name: "Norfolk Island",
      currency: "AUD",
      unicodeFlag: "🇳🇫",
      flag: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Norfolk_Island.svg",
      dialCode: "672",
    },
    {
      name: "Nigeria",
      currency: "NGN",
      unicodeFlag: "🇳🇬",
      flag: "https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg",
      dialCode: "234",
    },
    {
      name: "New Zealand",
      currency: "NZD",
      unicodeFlag: "🇳🇿",
      flag: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg",
      dialCode: "64",
    },
    {
      name: "Nepal",
      currency: "NPR",
      unicodeFlag: "🇳🇵",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg",
      dialCode: "977",
    },
    {
      name: "Nauru",
      currency: "AUD",
      unicodeFlag: "🇳🇷",
      flag: "https://upload.wikimedia.org/wikipedia/commons/3/30/Flag_of_Nauru.svg",
      dialCode: "674",
    },
    {
      name: "Niue",
      currency: "NZD",
      unicodeFlag: "🇳🇺",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Niue.svg",
      dialCode: "683",
    },
    {
      name: "Cook Islands",
      currency: "NZD",
      unicodeFlag: "🇨🇰",
      flag: "https://upload.wikimedia.org/wikipedia/commons/3/35/Flag_of_the_Cook_Islands.svg",
      dialCode: "682",
    },
    {
      name: "Kosovo",
      currency: "EUR",
      unicodeFlag: "🇽🇰",
    },
    {
      name: "Ivory Coast",
      currency: "XOF",
      unicodeFlag: "🇨🇮",
      dialCode: "225",
    },
    {
      name: "Switzerland",
      currency: "CHF",
      unicodeFlag: "🇨🇭",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_Switzerland_%28Pantone%29.svg",
      dialCode: "41",
    },
    {
      name: "Colombia",
      currency: "COP",
      unicodeFlag: "🇨🇴",
      flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg",
      dialCode: "57",
    },
    {
      name: "China",
      currency: "CNY",
      unicodeFlag: "🇨🇳",
      flag: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg",
      dialCode: "86",
    },
    {
      name: "Cameroon",
      currency: "XAF",
      unicodeFlag: "🇨🇲",
      flag: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg",
      dialCode: "237",
    },
    {
      name: "Chile",
      currency: "CLP",
      unicodeFlag: "🇨🇱",
      flag: "https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg",
      dialCode: "56",
    },
    {
      name: "Cocos Islands",
      currency: "AUD",
      unicodeFlag: "🇨🇨",
      dialCode: "61",
    },
    {
      name: "Canada",
      currency: "CAD",
      unicodeFlag: "🇨🇦",
      flag: "https://upload.wikimedia.org/wikipedia/en/c/cf/Flag_of_Canada.svg",
      dialCode: "1",
    },
    {
      name: "Congo",
      currency: "XAF",
      unicodeFlag: "🇨🇬",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_the_Republic_of_the_Congo.svg",
      dialCode: "242",
    },
    {
      name: "Central African Republic",
      currency: "XAF",
      unicodeFlag: "🇨🇫",
      flag: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Central_African_Republic.svg",
      dialCode: "236",
    },
    {
      name: "Democratic Republic of the Congo",
      currency: "CDF",
      unicodeFlag: "🇨🇩",
      dialCode: "243",
    },
    {
      name: "Czech Republic",
      currency: "CZK",
      unicodeFlag: "🇨🇿",
      flag: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg",
      dialCode: "420",
    },
    {
      name: "Cyprus",
      currency: "EUR",
      unicodeFlag: "🇨🇾",
      flag: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg",
      dialCode: "357",
    },
    {
      name: "Christmas Island",
      currency: "AUD",
      unicodeFlag: "🇨🇽",
      flag: "https://upload.wikimedia.org/wikipedia/commons/6/67/Flag_of_Christmas_Island.svg",
      dialCode: "61",
    },
    {
      name: "Costa Rica",
      currency: "CRC",
      unicodeFlag: "🇨🇷",
      flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Costa_Rica_%28state%29.svg",
      dialCode: "506",
    },
    {
      name: "Curacao",
      currency: "ANG",
      unicodeFlag: "🇨🇼",
      dialCode: "599",
    },
    {
      name: "Cape Verde",
      currency: "CVE",
      unicodeFlag: "🇨🇻",
      flag: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Cape_Verde.svg",
      dialCode: "238",
    },
    {
      name: "Cuba",
      currency: "CUP",
      unicodeFlag: "🇨🇺",
      flag: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg",
      dialCode: "53",
    },
    {
      name: "Swaziland",
      currency: "SZL",
      unicodeFlag: "🇸🇿",
      flag: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Flag_of_Eswatini.svg",
      dialCode: "268",
    },
    {
      name: "Syria",
      currency: "SYP",
      unicodeFlag: "🇸🇾",
      flag: "https://upload.wikimedia.org/wikipedia/commons/5/53/Flag_of_Syria.svg",
      dialCode: "963",
    },
    {
      name: "Sint Maarten",
      currency: "ANG",
      unicodeFlag: "🇸🇽",
      dialCode: "599",
    },
    {
      name: "Kyrgyzstan",
      currency: "KGS",
      unicodeFlag: "🇰🇬",
      flag: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Kyrgyzstan.svg",
      dialCode: "996",
    },
    {
      name: "Kenya",
      currency: "KES",
      unicodeFlag: "🇰🇪",
      flag: "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg",
      dialCode: "254",
    },
    {
      name: "South Sudan",
      currency: "SSP",
      unicodeFlag: "🇸🇸",
      dialCode: "211",
    },
    {
      name: "Suriname",
      currency: "SRD",
      unicodeFlag: "🇸🇷",
      flag: "https://upload.wikimedia.org/wikipedia/commons/6/60/Flag_of_Suriname.svg",
      dialCode: "597",
    },
    {
      name: "Kiribati",
      currency: "AUD",
      unicodeFlag: "🇰🇮",
      flag: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kiribati.svg",
      dialCode: "686",
    },
    {
      name: "Cambodia",
      currency: "KHR",
      unicodeFlag: "🇰🇭",
      flag: "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Cambodia.svg",
      dialCode: "855",
    },
    {
      name: "Saint Kitts and Nevis",
      currency: "XCD",
      unicodeFlag: "🇰🇳",
      flag: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg",
      dialCode: "+1-869",
    },
    {
      name: "Comoros",
      currency: "KMF",
      unicodeFlag: "🇰🇲",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/94/Flag_of_the_Comoros.svg",
      dialCode: "269",
    },
    {
      name: "Sao Tome and Principe",
      currency: "STD",
      unicodeFlag: "🇸🇹",
      flag: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Sao_Tome_and_Principe.svg",
      dialCode: "239",
    },
    {
      name: "Slovakia",
      currency: "EUR",
      unicodeFlag: "🇸🇰",
      flag: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg",
      dialCode: "421",
    },
    {
      name: "South Korea",
      currency: "KRW",
      unicodeFlag: "🇰🇷",
      dialCode: "82",
    },
    {
      name: "Slovenia",
      currency: "EUR",
      unicodeFlag: "🇸🇮",
      flag: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Slovenia.svg",
      dialCode: "386",
    },
    {
      name: "North Korea",
      currency: "KPW",
      unicodeFlag: "🇰🇵",
      dialCode: "850",
    },
    {
      name: "Kuwait",
      currency: "KWD",
      unicodeFlag: "🇰🇼",
      flag: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Kuwait.svg",
      dialCode: "965",
    },
    {
      name: "Senegal",
      currency: "XOF",
      unicodeFlag: "🇸🇳",
      flag: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Senegal.svg",
      dialCode: "221",
    },
    {
      name: "San Marino",
      currency: "EUR",
      unicodeFlag: "🇸🇲",
      flag: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_San_Marino.svg",
      dialCode: "378",
    },
    {
      name: "Sierra Leone",
      currency: "SLL",
      unicodeFlag: "🇸🇱",
      flag: "https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Sierra_Leone.svg",
      dialCode: "232",
    },
    {
      name: "Seychelles",
      currency: "SCR",
      unicodeFlag: "🇸🇨",
      flag: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Seychelles.svg",
      dialCode: "248",
    },
    {
      name: "Kazakhstan",
      currency: "KZT",
      unicodeFlag: "🇰🇿",
      flag: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg",
      dialCode: "7",
    },
    {
      name: "Cayman Islands",
      currency: "KYD",
      unicodeFlag: "🇰🇾",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_the_Cayman_Islands.svg",
      dialCode: "+1-345",
    },
    {
      name: "Singapore",
      currency: "SGD",
      unicodeFlag: "🇸🇬",
      flag: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg",
      dialCode: "65",
    },
    {
      name: "Sweden",
      currency: "SEK",
      unicodeFlag: "🇸🇪",
      flag: "https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg",
      dialCode: "46",
    },
    {
      name: "Sudan",
      currency: "SDG",
      unicodeFlag: "🇸🇩",
      flag: "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Sudan.svg",
      dialCode: "249",
    },
    {
      name: "Dominican Republic",
      currency: "DOP",
      unicodeFlag: "🇩🇴",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg",
      dialCode: "+1-809 and 1-829",
    },
    {
      name: "Dominica",
      currency: "XCD",
      unicodeFlag: "🇩🇲",
      flag: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Flag_of_Dominica.svg",
      dialCode: "+1-767",
    },
    {
      name: "Djibouti",
      currency: "DJF",
      unicodeFlag: "🇩🇯",
      flag: "https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_Djibouti.svg",
      dialCode: "253",
    },
    {
      name: "Denmark",
      currency: "DKK",
      unicodeFlag: "🇩🇰",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg",
      dialCode: "45",
    },
    {
      name: "British Virgin Islands",
      currency: "USD",
      unicodeFlag: "🇻🇬",
      dialCode: "+1-284",
    },
    {
      name: "Germany",
      currency: "EUR",
      unicodeFlag: "🇩🇪",
      flag: "https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg",
      dialCode: "49",
    },
    {
      name: "Yemen",
      currency: "YER",
      unicodeFlag: "🇾🇪",
      flag: "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Yemen.svg",
      dialCode: "967",
    },
    {
      name: "Algeria",
      currency: "DZD",
      unicodeFlag: "🇩🇿",
      flag: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg",
      dialCode: "213",
    },
    {
      name: "United States",
      currency: "USD",
      unicodeFlag: "🇺🇸",
      flag: "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg",
      dialCode: "1",
    },
    {
      name: "Uruguay",
      currency: "UYU",
      unicodeFlag: "🇺🇾",
      flag: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg",
      dialCode: "598",
    },
    {
      name: "Mayotte",
      currency: "EUR",
      unicodeFlag: "🇾🇹",
      flag: "https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg",
      dialCode: "262",
    },
    {
      name: "United States Minor Outlying Islands",
      currency: "USD",
      unicodeFlag: "🇺🇲",
      flag: "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg",
      dialCode: "1",
    },
    {
      name: "Lebanon",
      currency: "LBP",
      unicodeFlag: "🇱🇧",
      flag: "https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg",
      dialCode: "961",
    },
    {
      name: "Saint Lucia",
      currency: "XCD",
      unicodeFlag: "🇱🇨",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Saint_Lucia.svg",
      dialCode: "+1-758",
    },
    {
      name: "Laos",
      currency: "LAK",
      unicodeFlag: "🇱🇦",
      flag: "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Laos.svg",
      dialCode: "856",
    },
    {
      name: "Tuvalu",
      currency: "AUD",
      unicodeFlag: "🇹🇻",
      flag: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tuvalu.svg",
      dialCode: "688",
    },
    {
      name: "Taiwan",
      currency: "TWD",
      unicodeFlag: "🇹🇼",
      flag: "https://upload.wikimedia.org/wikipedia/commons/7/72/Flag_of_the_Republic_of_China.svg",
      dialCode: "886",
    },
    {
      name: "Trinidad and Tobago",
      currency: "TTD",
      unicodeFlag: "🇹🇹",
      flag: "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Trinidad_and_Tobago.svg",
      dialCode: "+1-868",
    },
    {
      name: "Turkey",
      currency: "TRY",
      unicodeFlag: "🇹🇷",
      flag: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
      dialCode: "90",
    },
    {
      name: "Sri Lanka",
      currency: "LKR",
      unicodeFlag: "🇱🇰",
      flag: "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg",
      dialCode: "94",
    },
    {
      name: "Liechtenstein",
      currency: "CHF",
      unicodeFlag: "🇱🇮",
      flag: "https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Liechtenstein.svg",
      dialCode: "423",
    },
    {
      name: "Latvia",
      currency: "EUR",
      unicodeFlag: "🇱🇻",
      flag: "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg",
      dialCode: "371",
    },
    {
      name: "Tonga",
      currency: "TOP",
      unicodeFlag: "🇹🇴",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Tonga.svg",
      dialCode: "676",
    },
    {
      name: "Lithuania",
      currency: "LTL",
      unicodeFlag: "🇱🇹",
      flag: "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg",
      dialCode: "370",
    },
    {
      name: "Luxembourg",
      currency: "EUR",
      unicodeFlag: "🇱🇺",
      flag: "https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Luxembourg.svg",
      dialCode: "352",
    },
    {
      name: "Liberia",
      currency: "LRD",
      unicodeFlag: "🇱🇷",
      flag: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Liberia.svg",
      dialCode: "231",
    },
    {
      name: "Lesotho",
      currency: "LSL",
      unicodeFlag: "🇱🇸",
      flag: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Flag_of_Lesotho.svg",
      dialCode: "266",
    },
    {
      name: "Thailand",
      currency: "THB",
      unicodeFlag: "🇹🇭",
      flag: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg",
      dialCode: "66",
    },
    {
      name: "French Southern Territories",
      currency: "EUR",
      unicodeFlag: "🇹🇫",
    },
    {
      name: "Togo",
      currency: "XOF",
      unicodeFlag: "🇹🇬",
      flag: "https://upload.wikimedia.org/wikipedia/commons/6/68/Flag_of_Togo.svg",
      dialCode: "228",
    },
    {
      name: "Chad",
      currency: "XAF",
      unicodeFlag: "🇹🇩",
      flag: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Chad.svg",
      dialCode: "235",
    },
    {
      name: "Turks and Caicos Islands",
      currency: "USD",
      unicodeFlag: "🇹🇨",
      flag: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg",
      dialCode: "+1-649",
    },
    {
      name: "Libya",
      currency: "LYD",
      unicodeFlag: "🇱🇾",
      dialCode: "218",
    },
    {
      name: "Vatican",
      currency: "EUR",
      unicodeFlag: "🇻🇦",
      dialCode: "379",
    },
    {
      name: "Saint Vincent and the Grenadines",
      currency: "XCD",
      unicodeFlag: "🇻🇨",
      flag: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg",
      dialCode: "+1-784",
    },
    {
      name: "United Arab Emirates",
      currency: "AED",
      unicodeFlag: "🇦🇪",
      flag: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg",
      dialCode: "971",
    },
    {
      name: "Andorra",
      currency: "EUR",
      unicodeFlag: "🇦🇩",
      flag: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Andorra.svg",
      dialCode: "376",
    },
    {
      name: "Antigua and Barbuda",
      currency: "XCD",
      unicodeFlag: "🇦🇬",
      flag: "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Antigua_and_Barbuda.svg",
      dialCode: "+1-268",
    },
    {
      name: "Afghanistan",
      currency: "AFN",
      unicodeFlag: "🇦🇫",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Afghanistan.svg",
      dialCode: "93",
    },
    {
      name: "Anguilla",
      currency: "XCD",
      unicodeFlag: "🇦🇮",
      flag: "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Anguilla.svg",
      dialCode: "+1-264",
    },
    {
      name: "U.S. Virgin Islands",
      currency: "USD",
      unicodeFlag: "🇻🇮",
      dialCode: "+1-340",
    },
    {
      name: "Iceland",
      currency: "ISK",
      unicodeFlag: "🇮🇸",
      flag: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg",
      dialCode: "354",
    },
    {
      name: "Iran",
      currency: "IRR",
      unicodeFlag: "🇮🇷",
      flag: " https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg",
      dialCode: "98",
    },
    {
      name: "Armenia",
      currency: "AMD",
      unicodeFlag: "🇦🇲",
      flag: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Armenia.svg",
      dialCode: "374",
    },
    {
      name: "Albania",
      currency: "ALL",
      unicodeFlag: "🇦🇱",
      flag: "https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg",
      dialCode: "355",
    },
    {
      name: "Angola",
      currency: "AOA",
      unicodeFlag: "🇦🇴",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Angola.svg",
      dialCode: "244",
    },
    {
      name: "Antarctica",
      unicodeFlag: "🇦🇶",
    },
    {
      name: "American Samoa",
      currency: "USD",
      unicodeFlag: "🇦🇸",
      dialCode: "+1-684",
    },
    {
      name: "Argentina",
      currency: "ARS",
      unicodeFlag: "🇦🇷",
      flag: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
      dialCode: "54",
    },
    {
      name: "Australia",
      currency: "AUD",
      unicodeFlag: "🇦🇺",
      flag: "https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Australia_%28converted%29.svg",
      dialCode: "61",
    },
    {
      name: "Austria",
      currency: "EUR",
      unicodeFlag: "🇦🇹",
      flag: "https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg",
      dialCode: "43",
    },
    {
      name: "Aruba",
      currency: "AWG",
      unicodeFlag: "🇦🇼",
      flag: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Aruba.svg",
      dialCode: "297",
    },
    {
      name: "India",
      currency: "INR",
      unicodeFlag: "🇮🇳",
      flag: "https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg",
      dialCode: "91",
    },
    {
      name: "Aland Islands",
      currency: "EUR",
      unicodeFlag: "🇦🇽",
      dialCode: "+358-18",
    },
    {
      name: "Azerbaijan",
      currency: "AZN",
      unicodeFlag: "🇦🇿",
      flag: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg",
      dialCode: "994",
    },
    {
      name: "Ireland",
      currency: "EUR",
      unicodeFlag: "🇮🇪",
      flag: "https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg",
      dialCode: "353",
    },
    {
      name: "Indonesia",
      currency: "IDR",
      unicodeFlag: "🇮🇩",
      flag: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg",
      dialCode: "62",
    },
    {
      name: "Ukraine",
      currency: "UAH",
      unicodeFlag: "🇺🇦",
      flag: "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg",
      dialCode: "380",
    },
    {
      name: "Qatar",
      currency: "QAR",
      unicodeFlag: "🇶🇦",
      flag: "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg",
      dialCode: "974",
    },
    {
      name: "Mozambique",
      currency: "MZN",
      unicodeFlag: "🇲🇿",
      flag: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Mozambique.svg",
      dialCode: "258",
    },
  ],
});

export const getters = {
  categoriesList(state) {
    return state.categoriesList;
  },
  productsList(state) {
    return state.productsList;
  },
  shippingPriceList(state) {
    return state.shippingPriceList;
  },
  countriesList(state) {
    return state.countriesList;
  },
  statesByCountryList(state) {
    return state.statesByCountryList;
  },
  citiesByStatesList(state) {
    return state.citiesByStatesList;
  },
  colorsList(state) {
    return state.colorsList;
  },
  statusList(state) {
    return state.statusList;
  },
  // statusListRtl(state) {
  //   return state.statusListRtl;
  // },
};

export const actions = {
  getCategoriesFromApi({ commit }, payload) {
    commit("categoriesList", payload);
  },
  getProductsFromApi({ commit }, payload) {
    commit("productsList", payload);
  },
  shippingPriceList({ commit }, payload) {
    commit("shippingPriceList", payload);
  },
  updateCountriesList({ commit }, payload) {
    commit("countriesList", payload);
  },
  updateStatesByCountryList({ commit }, payload) {
    commit("statesByCountryList", payload);
  },
  updateCitiesByStatesList({ commit }, payload) {
    commit("citiesByStatesList", payload);
  },
  getAllColors({ commit }, payload) {
    commit("colorsList", payload);
  },
};

export const mutations = {
  categoriesList(state, val) {
    state.categoriesList = val;
  },
  shippingPriceList(state, val) {
    state.shippingPriceList = val;
  },
  productsList(state, val) {
    state.productsList = val;
  },
  countriesList(state, val) {
    state.countriesList = val;
  },
  statesByCountryList(state, val) {
    state.statesByCountryList = val;
  },
  citiesByStatesList(state, val) {
    state.citiesByStatesList = val;
  },
  colorsList(state, val) {
    state.colorsList = val;
  },
};
